# Generated by Django 5.0 on 2023-12-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
